version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    # volumes:
    #   - 'zookeeper_data:/bitnami'

  kafka:
    image: 'bitnami/kafka:latest'
    hostname: localhost
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    # volumes:
    #   - 'kafka_data:/bitnami'
    depends_on:
      - zookeeper
  publisher:
    build:
      context: ./Producer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
  consumer:
    build:
      context: ./Consumer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
#   kafka-ui:
#     image: 'provectuslabs/kafka-ui:latest'
#     ports:
#       - '8080:8080'
#     environment:
#       - KAFKA_CLUSTERS_0_NAME=local
#       - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
#       - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
#     depends_on:
#       - kafka

# volumes:
#   zookeeper_data:
#     driver: local
#   kafka_data:
#     driver: local
